title: Personal Portfolio
author: Daniel Sobral
email: dv.sobral@fct.unl.pt
description: > # this means to ignore newlines until "baseurl:"
  I a Bioinformatician with 10+ years experience in academia.
  I will show some of the stuff I have done professionally.

theme: minima

# social links
github_username:  dsobral # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
